const ENTERPRISE_ID_ZEMO = 1;
const ENTERPRISE_ID_WINKLER = 8; // 博仲
const ENTERPRISE_ID_JWCPAS = 11;
const ENTERPRISE_ID_WISTRON = 16; // 緯創
const ENTERPRISE_ID_ASUS = 21; // 華碩
const ENTERPRISE_ID_PEGATRON = 24; // 和碩
const ENTERPRISE_ID_AUO = 25; // 友達
const ENTERPRISE_ID_GOGORO = 26;
const ENTERPRISE_ID_MSI = 27; // 微星
const ENTERPRISE_ID_AZUREWAVE = 34; // 海華
const ENTERPRISE_ID_ACER = 35; // 宏碁
const ENTERPRISE_ID_CHAILEASE = 36; // 中租
const ENTERPRISE_ID_STARSAFEYOU = 37; // 星安
const ENTERPRISE_ID_ADLINKTECH = 39; // 凌華
const ENTERPRISE_ID_EINK = 40; // 元太
const ENTERPRISE_ID_KKDAY = 41;
const ENTERPRISE_ID_KLOOK = 42;
const ENTERPRISE_ID_24TMS = 43; // 全鋒
const ENTERPRISE_ID_HULANE = 44; // 胡連精密
const ENTERPRISE_ID_AXIOMTEK = 45; // 艾訊
const ENTERPRISE_ID_SYSGRATION = 46; // 系統電子
const ENTERPRISE_ID_DONKEY = 47; // 小驢駒
const ENTERPRISE_ID_FENC = 48; // 遠東新世紀

const HIGH_PRIORITY_ENTERPRISES = new Set([
	ENTERPRISE_ID_ZEMO,
	ENTERPRISE_ID_ASUS,
	ENTERPRISE_ID_AUO,
	ENTERPRISE_ID_WISTRON,
	ENTERPRISE_ID_PEGATRON,
	ENTERPRISE_ID_EINK,
	ENTERPRISE_ID_ADLINKTECH,
	ENTERPRISE_ID_ACER,
	ENTERPRISE_ID_AZUREWAVE,
]);

const LOW_PRIORITY_ENTERPRISES = new Set([
	ENTERPRISE_ID_KKDAY,
	ENTERPRISE_ID_KLOOK,
	ENTERPRISE_ID_24TMS,
	ENTERPRISE_ID_STARSAFEYOU,
]);

module.exports = {
	ENTERPRISE_ID_ZEMO,
	ENTERPRISE_ID_ASUS,
	ENTERPRISE_ID_JWCPAS,
	ENTERPRISE_ID_WISTRON,
	ENTERPRISE_ID_WINKLER,
	ENTERPRISE_ID_PEGATRON,
	ENTERPRISE_ID_AUO,
	ENTERPRISE_ID_GOGORO,
	ENTERPRISE_ID_MSI,
	ENTERPRISE_ID_ACER,
	ENTERPRISE_ID_CHAILEASE,
	ENTERPRISE_ID_ADLINKTECH,
	ENTERPRISE_ID_EINK,
	ENTERPRISE_ID_KKDAY,
	ENTERPRISE_ID_KLOOK,
	ENTERPRISE_ID_HULANE,
	ENTERPRISE_ID_AXIOMTEK,
	ENTERPRISE_ID_SYSGRATION,
	ENTERPRISE_ID_DONKEY,
	ENTERPRISE_ID_FENC,
	HIGH_PRIORITY_ENTERPRISES,
	LOW_PRIORITY_ENTERPRISES,
};
